server:
  port: 8080
application:
  clear-command-cron: "0 */5 * * * *"
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/justice_telegram_bot"
    username: justapp
    password: 1
  main:
    allow-circular-references: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate